### PR TITLE
Update node-sass dependency

### PR DESCRIPTION
**Pull request by evanfuture**
There is an issue with watchers in the latest version of node-sass.  This fixes us to to the last version that worked.  Fixes issue https://github.com/NativeScript/nativescript-dev-sass/issues/47

### CODE REVIEW

**Review by vakrilov — APPROVED** [review]

**Comment by vakrilov** [comment]
Thanks @evanfuture!

**Comment by datanotion** [comment]
This was driving me crazy - I must have been running an older version, as it seems to work now.

**As a side note**, this issue was fixed 2 days ago in node-sass:  https://github.com/sass/node-sass/pull/2151/files

Question though - nativescript-dev-sass still seems to be transferring the .sass file to the device as well - is that what is causing the app to restart even on style changes?

image

**Comment by evanfuture** [comment]
I'll keep an eye on that fix, and make another PR here to bump the version once it's out of pre-release (4.7.0) and I test it out of course.

I don't know about the sass files, but yes, that would trigger a restart.  I thought I read somewhere that it would be nice to not have them transfer, but no one had the time to take that up.  Not sure!

**Comment by evanfuture** [comment]
Ok, checked it out and made a PR: https://github.com/NativeScript/nativescript-dev-sass/pull/51  Works well!

**Pull request merged**
